services:
  nginx:
    container_name: nginx
    image: nginx:1.22.0
    network_mode: host
    restart: unless-stopped
    cap_drop:
      - "ALL"
    cap_add:
      - "CAP_CHOWN"
      #- "CAP_DAC_OVERRIDE"
      - "CAP_SETGID"
      - "CAP_SETUID"
      - "CAP_NET_BIND_SERVICE"
    read_only: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config:/etc/nginx/conf.d:ro
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/default/error.html:/usr/share/nginx/html/error.html:ro
      - ./www/default/network.html:/usr/share/nginx/html/network.html:ro
      - ./www/nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./www/nginx/security.txt:/usr/share/nginx/html/secuity.txt:ro
      - ./www/nginx/robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./logs:/var/log/nginx:rw
      - ./tmp/cache:/var/cache/nginx:rw
      - ./tmp/run:/var/run/nginx:rw
    tmpfs:
      - "/tmp:exec,uid=999,gid=999"
    logging: 
      driver: json-file
      options:
        max-size: 50m
    deploy:
      resources:
        limits:
          cpus: '3.00' # 1 = core
          memory: '5G' # 1 1G = 1GB ram