version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx:1.22.0
    network_mode: host
    restart: unless-stopped
    cap_drop:
      - "ALL"
    read_only: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www/default/error.html:/usr/share/nginx/html/error.html:ro
      - ./www/default/network.html:/usr/share/nginx/html/network.html:ro
      - ./www/nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./www/nginx/security.txt:/usr/share/nginx/html/secuity.txt:ro
      - ./www/nginx/robots.txt:/usr/share/nginx/html/robots.txt:ro
    tmpfs:
      - "/tmp:exec,uid=999,gid=999"
    logging: 
      driver: json-file
      options:
        max-size: 50m
    deploy:
      #mode: replicated
      #replicas: 3
      resources:
        limits:
          cpus: '3.00' # 1 = core
          memory: '5G' # 1 1G = 1GB ram